sudo: false
dist: trusty
language: python
python:
    - 3.6.1  # This should match with runtime.txt
before_install:
    - git clone --depth=50 --branch=master https://github.com/UnivaqTelegramBot/UnivaqInformaticaBot ~/UnivaqInformaticaBot
    - cp *.py ~/UnivaqInformaticaBot  # copy local pytest scripts into ~/UnivaqInformaticaBot
    - cd ~/UnivaqInformaticaBot
install:
    - pip install flake8 pytest
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --statistics
    # exit-zero treates all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script: true
    # pytest --capture=sys
    # python unittest.py
notifications:
    on_success: change
    on_failure: never  # always will be the setting once code changes slow down
